
name: armTenplateDeployment

 
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  armDeploy:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Resource Group with AZ CLI
        uses: Azure/cli@v1
        with:
          inlinescript: |
           az deployment sub create --location "Australia East" --template-file ./arm-templates/resourcegroup.json

