
name: armTenplateDeployment

 
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  resource_group_name: rg-githubactions
  location: "Australia East"
  subscriptionId: c78477d4-1241-41e8-89a4-8453626b3798
jobs:
  armDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Resource Group ${{ env.resource_group_name }}
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ env.subscriptionId }}
          region: ${{ env.location }}
          template: ./arm_templates/resourcegroup.json
          parameters:
            location="${{ env.location }}"
            resourceGroupName=${{ env.resource_group_name }}
          deploymentName: ${{ env.resource_group_name }}

      - name: Deploy Storage Account
        uses: Azure/arm-deploy@v1
        id: storageAccountDeploy
        with:
          scope: resourcegroup
          resourceGroupName: ${{ env.resource_group_name }}
          subscriptionId: ${{ env.subscriptionId }}
          template: ./arm_templates/storageaccount.json
          parameters:
           sku=Standard_LRS
           storageAccountName=globostg002iuqname
           location="${{ env.location }}"
          deploymentMode: incremental

      - name: Deploy Vitual machine
        uses: Azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: ${{ env.resource_group_name }}
          subscriptionId: ${{ env.subscriptionId }}
          template: ./arm_templates/virtualmachine.json
          parameters:
            adminPassword=${{ secrets.UBUNTU_ADMIN_PASSWORD }}
            location="${{ env.location }}"
          deploymentMode: incremental



      
